WeatherCity/Models/Context.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WeatherCity.Models
{
	public class Context : DbContext
	{
		public Context(DbContextOptions<Context> options) : base(options) { }
		public DbSet<Municipio> Municipios { get; set; }


	}
}

WeatherCity/Models/ErrorViewModel.cs
using System;

namespace WeatherCity.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

WeatherCity/Models/Municipio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WeatherCity.Models
{

	public class Municipio
	{

		public int Id { get; set; }

		[Required(ErrorMessage = "O campo Nome deve ser preenchido.")]
		public string Nome { get; set; }

		[Display(Name = "Inserido em")]
		public DateTime? DataCriacao { get; set; }

		[Display(Name = "Atualizado em")]
		public DateTime? DataAlteracao { get; set; }
	}
}

WeatherCity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WeatherCity.Models;

namespace WeatherCity.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult About()
		{
			ViewData["Message"] = "Your application description page.";

			return View();
		}

		public IActionResult Contact()
		{
			ViewData["Message"] = "Your contact page.";

			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

WeatherCity/Controllers/MunicipiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WeatherCity.Models;

namespace WeatherCity.Controllers
{
    public class MunicipiosController : Controller
    {
        private readonly Context _context;

        public MunicipiosController(Context context)
        {
            _context = context;
        }

        // GET: Municipios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Municipios.ToListAsync());
        }

        // GET: Municipios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var municipio = await _context.Municipios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (municipio == null)
            {
                return NotFound();
            }

            return View(municipio);
        }

        // GET: Municipios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Municipios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,DataCriacao,DataAlteracao")] Municipio municipio)
        {
            if (ModelState.IsValid)
            {
				municipio.DataCriacao = DateTime.Now;
				municipio.DataAlteracao = DateTime.Now;

				_context.Add(municipio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(municipio);
        }

        // GET: Municipios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var municipio = await _context.Municipios.FindAsync(id);
            if (municipio == null)
            {
                return NotFound();
            }
            return View(municipio);
        }

        // POST: Municipios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,DataCriacao,DataAlteracao")] Municipio municipio)
        {
            if (id != municipio.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
				municipio.DataAlteracao = DateTime.Now;

                try
                {
                    _context.Update(municipio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MunicipioExists(municipio.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(municipio);
        }

        // GET: Municipios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var municipio = await _context.Municipios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (municipio == null)
            {
                return NotFound();
            }

            return View(municipio);
        }

        // POST: Municipios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var municipio = await _context.Municipios.FindAsync(id);
            _context.Municipios.Remove(municipio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MunicipioExists(int id)
        {
            return _context.Municipios.Any(e => e.Id == id);
        }
    }
}

WeatherCity/Views/Home/About.cshtml
<div class="row">
	<div class="col-md-12">
		<div class="note note-info">
			<h4 class="block">Objetivo do projeto:</h4>
			<p>Desenvolver uma aplicação WEB que permite cadastrar cidade e exibir a previsão do tempo com o intuíto de aprender mais sobre .NetCore MVC.</p>
			<p>Para isso foi criado uma interna API que consume a API do http://openweathermap.org, evitando assim CORS (Cross-Origin Resource Sharing). </p>
			<p>Foi criado um projeto para testar essa API dentro da Web Application.</p>
			<p>Toda elemento que apresenta a previsão do tempo é componente Vue.js. </p>
			<br />
			<h4 class="block">Stack do projeto:</h4>
			<p>.Net Core 2.1</p>
			<p>MVC Web Application</p>
			<p>Flurl</p>
			<p>Vue.Js</p>
			<p>Vue Resources</p>
			<p>JQuery</p>
			<p>Metronic</p>
			<p>Datatables</p>
			<p>Xunit</p>
			<p>Newtonsoft</p>
		</div>
	</div>
</div>

WeatherCity/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contato";
}
<div class="row">
	<div class="col-md-12">
		<div class="note note-info">
			<h4 class="block">César Albuquerque:</h4>
			<p>
				Entusiasta de novas tecnologias e apaixonado por front-end, tenho objetivo de colaborar em um ambiente de trabalho onde possa colocar em prática meus conhecimentos em favor da instituição,
				focando sempre no benefício e crescimento da organização assim como no trabalho em equipe para o crescimento profissional.
			</p>
			<strong>E-mail:</strong> <a href="mailto:cesartdealbuquerque@gmail.com">cesartdealbuquerque@gmail.com</a><br />
			<strong>LinkdIn:</strong> <a href="https://www.linkedin.com/in/cesaralbuquerque/" target="_blank">linkedin.com/in/cesaralbuquerque</a><br />
			<strong>GitLab:</strong> <a href="https://gitlab.com/cesaralbuquerque" target="_blank">gitlab.com/cesaralbuquerque</a>
		</div>
	</div>
</div>

WeatherCity/Views/Municipios/Create.cshtml
@model WeatherCity.Models.Municipio

<div class="portlet light bordered">
	<div class="portlet-title">
		<div class="caption">
			<i class="icon-settings font-dark"></i>
			<span class="caption-subject font-dark sbold uppercase">Novo município</span>
		</div>
	</div>
	<div class="portlet-body form">
		<form class="form-horizontal" role="form" asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-body">
				<div class="form-group">
					<label asp-for="Nome" class="control-label col-md-3"></label>
					<div class="col-md-9">
						<input asp-for="Nome" class="form-control" placeholder="Exemplo: Blumenau" />
						<span asp-validation-for="Nome" class="text-danger"></span>
					</div>
				</div>
			</div>
			<div class="form-actions">
				<button type="submit" value="Create" class="btn blue">Salvar</button>
				<a class="btn default" asp-action="Index">Cancelar</a>
			</div>
		</form>
	</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WeatherCity/Views/Municipios/Delete.cshtml
@model WeatherCity.Models.Municipio

<div class="portlet light bordered">
	<div class="portlet-title">
		<div class="caption">
			<i class="icon-settings font-dark"></i>
			<span class="caption-subject font-dark sbold uppercase">Excluir município</span>
		</div>
	</div>
	<div class="portlet-body form">
		<form class="form-horizontal" role="form" asp-action="Delete">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-body">
				<div class="form-group">
					<label asp-for="Nome" class="control-label col-md-3"></label>
					<div class="col-md-9">
						<p class="form-control-static"> @Html.Raw(Model.Nome) </p>
					</div>
				</div>
				<div class="form-group">
					<label asp-for="DataCriacao" class="control-label col-md-3"></label>
					<div class="col-md-9">
						<p class="form-control-static"> @Html.Raw(Model.DataCriacao) </p>
					</div>
				</div>
				<div class="form-group">
					<label asp-for="DataAlteracao" class="control-label col-md-3"></label>
					<div class="col-md-9">
						<p class="form-control-static"> @Html.Raw(Model.DataAlteracao) </p>
					</div>
				</div>
			</div>
			<div class="form-actions">
				<input type="hidden" asp-for="Id" />
				<input type="submit" value="Excluir" class="btn red" />
				<a class="btn default" asp-action="Index">Cancelar</a>
			</div>
		</form>
	</div>
</div>

WeatherCity/Views/Municipios/Details.cshtml
@model WeatherCity.Models.Municipio

<div class="portlet light bordered">
	<div class="portlet-title">
		<div class="caption">
			<i class="icon-settings font-dark"></i>
			<span class="caption-subject font-dark sbold uppercase">Tempo agora</span>
		</div>
	</div>
	<div class="portlet-body form">
		<form class="form-horizontal" role="form" asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-body">
				<div class="form-group">
					<label asp-for="Nome" class="control-label col-md-3"></label>
					<div class="col-md-9">
						<p class="form-control-static"> @Html.Raw(Model.Nome) </p>
					</div>
				</div>
				<div class="form-group">
					<label asp-for="DataCriacao" class="control-label col-md-3"></label>
					<div class="col-md-9">
						<p class="form-control-static"> @Html.Raw(Model.DataCriacao) </p>
					</div>
				</div>
				<div class="form-group">
					<label asp-for="DataAlteracao" class="control-label col-md-3"></label>
					<div class="col-md-9">
						<p class="form-control-static"> @Html.Raw(Model.DataAlteracao) </p>
					</div>
				</div>
			</div>
			<div class="form-actions">
				<input type="hidden" asp-for="Id" />
				<a class="btn green" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
				<a class="btn default" asp-action="Index">Cancelar</a>
			</div>
		</form>
	</div>
</div>

<div id="weather">
	<div class="row">
		<div class="col-lg-offset-3 col-lg-6 col-md-12 col-sm-12 col-xs-12">
			<weather city="@Html.Raw(Model.Nome)"></weather>
		</div>
	</div>
</div>

<div id="miniweather">
	<div class="row">
		<div class="col-lg-offset-3 col-lg-6 col-md-12 col-sm-12 col-xs-12">
			<mini-weather city="@Html.Raw(Model.Nome)"></mini-weather>
		</div>
	</div>
</div>
<script>
new Vue({
	el: '#weather'
	});
</script>

WeatherCity/Views/Municipios/Edit.cshtml
@model WeatherCity.Models.Municipio

<div class="portlet light bordered">
	<div class="portlet-title">
		<div class="caption">
			<i class="icon-settings font-dark"></i>
			<span class="caption-subject font-dark sbold uppercase">Editar município</span>
		</div>
	</div>
	<div class="portlet-body form">
		<form class="form-horizontal" role="form" asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-body">
				<div class="form-group">
					<label asp-for="Nome" class="control-label col-md-3"></label>
					<div class="col-md-9">
						<input asp-for="Nome" class="form-control" placeholder="Exemplo: Blumenau" />
						<span asp-validation-for="Nome" class="text-danger"></span>
					</div>
				</div>
				<div class="form-group">
					<label asp-for="DataCriacao" class="control-label col-md-3"></label>
					<div class="col-md-9">
						<input type="hidden" asp-for="DataCriacao" />
						<input asp-for="DataCriacao" class="form-control" disabled/>
					</div>
				</div>
				<div class="form-group">
					<label asp-for="DataAlteracao" class="control-label col-md-3"></label>
					<div class="col-md-9">
						<input type="hidden" asp-for="DataAlteracao" />
						<input asp-for="DataAlteracao" class="form-control" disabled/>
					</div>
				</div>
			</div>
			<div class="form-actions">
				<input type="hidden" asp-for="Id" />
				<button type="submit" value="Save" class="btn blue">Salvar</button>
				<a class="btn default" asp-action="Index">Cancelar</a>
			</div>
		</form>
	</div>
</div>



@*<h4>Municipio</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<label asp-for="Nome" class="control-label"></label>
				<input asp-for="Nome" class="form-control" />
				<span asp-validation-for="Nome" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="DataCriacao" class="control-label"></label>
				<input asp-for="DataCriacao" class="form-control" />
				<span asp-validation-for="DataCriacao" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="DataAlteracao" class="control-label"></label>
				<input asp-for="DataAlteracao" class="form-control" />
				<span asp-validation-for="DataAlteracao" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-default" />
			</div>
		</form>
	</div>
</div>*@


@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WeatherCity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.7
Version: 4.7.1
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->

<head>
	<meta charset="utf-8" />
	<title>Weather City Project</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1" name="viewport" />
	<meta content="Esse projeto tem o objetivo de aprender e exercitar conceitos." name="description" />
	<meta content="César Albuquerque" name="author" />
	<!-- BEGIN GLOBAL MANDATORY STYLES -->
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
	<link href="~/Content/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
	<script src="~/Content/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN THEME GLOBAL STYLES -->
	<link href="~/Content/assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
	<link href="~/Content/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
	<!-- END THEME GLOBAL STYLES -->
	<!-- BEGIN THEME LAYOUT STYLES -->
	<link href="~/Content/assets/layouts/layout/css/layout.min.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/assets/layouts/layout/css/themes/darkblue.min.css" rel="stylesheet" type="text/css" id="style_color" />
	<link href="~/Content/assets/layouts/layout/css/custom.min.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css">
	<link href="~/Content/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
	<!-- END THEME LAYOUT STYLES -->
	<!-- BEGIN LOADER SCRIPT -->
	<script src="~/dist/site.bundle.js"></script>
	<!-- END LOADER SCRIPT -->
</head>
<!-- END HEAD -->

<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white page-full-width">
	<div class="page-wrapper">
		<!-- BEGIN HEADER -->
		<div class="page-header navbar navbar-fixed-top">
			<!-- BEGIN HEADER INNER -->
			<div class="page-header-inner ">
				<!-- BEGIN MEGA MENU -->
				<!-- DOC: Remove "hor-menu-light" class to have a horizontal menu with theme background instead of white background -->
				<!-- DOC: This is desktop version of the horizontal menu. The mobile version is defined(duplicated) in the responsive menu below along with sidebar menu. So the horizontal menu has 2 seperate versions -->
				<div class="hor-menu   hidden-sm hidden-xs">
					<ul class="nav navbar-nav">
						<!-- DOC: Remove data-hover="megamenu-dropdown" and data-close-others="true" attributes below to disable the horizontal opening on mouse hover -->
						<li is-active-route asp-controller="Home" asp-action="About" class="classic-menu-dropdown" aria-haspopup="true">
							<a asp-area="" asp-controller="Home" asp-action="About">
								Sobre o projeto
								<span class=""> </span>
							</a>
						</li>
						<li is-active-route asp-controller="Home" asp-action="Contact" class="classic-menu-dropdown" aria-haspopup="true">
							<a asp-area="" asp-controller="Home" asp-action="Contact">
								Contato
								<span class=""> </span>
							</a>
						</li>
						<li is-active-route asp-controller="Municipios" asp-action="Index" class="classic-menu-dropdown" aria-haspopup="true">
							<a asp-area="" asp-controller="Municipios" asp-action="Index">
								Municípios
								<span class=""> </span>
							</a>
						</li>
					</ul>
				</div>
				<!-- END MEGA MENU -->
				<!-- BEGIN HEADER SEARCH BOX -->
				<!-- DOC: Apply "search-form-expanded" right after the "search-form" class to have half expanded search box -->
				<form id="quick-search" class="search-form">
					<div class="input-group">
						<input id="quick-search-city" type="text" class="form-control" placeholder="Pesquisa rápida...">
						<span class="input-group-btn">
							<a href="javascript:;" class="btn submit">
								<i class="icon-magnifier"></i>
							</a>
						</span>
					</div>
				</form>
				<!-- END HEADER SEARCH BOX -->
				<!-- BEGIN RESPONSIVE MENU TOGGLER -->
				<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
					<span></span>
				</a>
				<!-- END RESPONSIVE MENU TOGGLER -->
			</div>
			<!-- END HEADER INNER -->
		</div>
		<!-- END HEADER -->
		<!-- BEGIN HEADER & CONTENT DIVIDER -->
		<div class="clearfix"> </div>
		<!-- END HEADER & CONTENT DIVIDER -->
		<!-- BEGIN CONTAINER -->
		<div class="page-container">
			<!-- BEGIN SIDEBAR -->
			<div class="page-sidebar-wrapper">
				<div class="page-sidebar navbar-collapse collapse">
					<ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
						<li is-active-route asp-controller="Home" asp-action="About" class="classic-menu-dropdown" aria-haspopup="true">
							<a asp-area="" asp-controller="Home" asp-action="About">
								Sobre o projeto
								<span class=""> </span>
							</a>
						</li>
						<li is-active-route asp-controller="Home" asp-action="Contact" class="classic-menu-dropdown" aria-haspopup="true">
							<a asp-area="" asp-controller="Home" asp-action="Contact">
								Contato
								<span class=""> </span>
							</a>
						</li>
						<li is-active-route asp-controller="Municipios" asp-action="Index" class="classic-menu-dropdown" aria-haspopup="true">
							<a asp-area="" asp-controller="Municipios" asp-action="Index">
								Municípios
								<span class=""> </span>
							</a>
						</li>
					</ul>
				</div>
			</div>
			<!-- END SIDEBAR -->
			<!-- BEGIN CONTENT -->
			<div class="page-content-wrapper">
				<!-- BEGIN CONTENT BODY -->
				<div class="page-content" style="min-height: 657px;">
					@RenderBody()
				</div>
				<!-- BEGIN QUICK SEARCH MODAL-->
				<div id="quick-seach-modal" class="modal fade" tabindex="-1" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
								<h4 class="modal-title">Tempo Agora</h4>
							</div>
							<div class="modal-body">
								<div class="scroller" style="height:300px" data-always-visible="1" data-rail-visible1="1">
									<div class="row">
										<div id="quick-weather">
											<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 quick-weather-tile">

											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- END QUICK SEARCH MODAL-->
				<!-- END CONTENT BODY -->
			</div>
			<!-- END CONTENT -->
		</div>
		<!-- END CONTAINER -->
		<!-- BEGIN FOOTER -->
		<div class="page-footer">
			<div class="page-footer-inner">
				@DateTime.Now.Year &copy; César Albuquerque &nbsp;|&nbsp;
				<a target="_blank" href="https://gitlab.com/cesaralbuquerque"><i class="fa fa-git"></i></a> &nbsp;|&nbsp;
				<a target="_blank" href="https://www.linkedin.com/in/cesaralbuquerque/"><i class="fa fa-linkedin"></i></a>
			</div>
			<div class="scroll-to-top">
				<i class="icon-arrow-up"></i>
			</div>
		</div>
		<!-- END FOOTER -->
	</div>
	<!--[if lt IE 9]>
	<script src="~/Content/assets/global/plugins/respond.min.js"></script>
	<script src="~/Content/assets/global/plugins/excanvas.min.js"></script>
	<script src="~/Content/assets/global/plugins/ie8.fix.min.js"></script>
	<![endif]-->
	<!-- BEGIN CORE PLUGINS -->
	<script src="~/Content/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="~/Content/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
	<script src="~/Content/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
	<script src="~/Content/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
	<script src="~/Content/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
	<!-- END CORE PLUGINS -->
	<!-- BEGIN THEME GLOBAL SCRIPTS -->
	<script src="~/Content/assets/global/scripts/app.min.js" type="text/javascript"></script>
	<!-- END THEME GLOBAL SCRIPTS -->
	<!-- BEGIN THEME LAYOUT SCRIPTS -->
	<script src="~/Content/assets/layouts/layout/scripts/layout.min.js" type="text/javascript"></script>
	<script src="~/Content/assets/layouts/layout/scripts/demo.min.js" type="text/javascript"></script>
	<script src="~/Content/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
	<script src="~/Content/assets/layouts/global/scripts/quick-nav.min.js" type="text/javascript"></script>
	<script src="~/Content/assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
	<script src="~/Content/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>

	<script>
		QuickSearchInit();
		WeatherTableInit();
	</script>


	<!-- END THEME LAYOUT SCRIPTS -->
	@RenderSection("Scripts", required: false)
</body>

</html>